### ISSUE TITLE
(Feature suggestion) User editable scrapers for comics and novels

### ISSUE THREAD

**Issue by zeoint** [manga-download/haruneko#290]
Please bear with me, I don't know a thing about coding.

1. Provide users to make new scrapers based on the default scraper if there is no scraper for a website and the ability to name, save, and edit the custom scraper with guidance (See Reference).
2. I request this feature as the websites change their url frequently due to dmce, other reasons, but the underlying mechanism/code might be the same with new url name instead of old url name in the code. And many websites might work with the same scraper with url change as they are clones, etc.
3. For example, A url change of a website from scanlationcomics.com to scanlationcomics.to or .net or scancomics.com, etc, the underlying code might not change excpet for the name containing the old URL. In those scenarios this feature would help users a lot. So the work load / website suggestion requests would reduce as the user can change them.
4. This is one of the uses of this feature request, but this feature could be improved on.

---

Reference - [Webtoepub](https://dteviot.github.io/Projects/webToEpub_DefaultParser.html)

1. It is a browser extension that scrapes text, but you get the gist of it.

**Comment by MikeZeDev** [comment]
2) If a website is found to change url too often, it then should be given an url override setting, and the rest of the plugin coded accordingly to accomodate those change (using ValidateMangaUrl and a more lose regexp)

**Comment by Sheepux** [comment]
1. is still the same as current documentation, just write a connector or create a userplugin
https://github.com/manga-download/hakuneko/wiki/Developer-Website-Tutorial
https://hakuneko.download/docs/install/#user-plugins
3. As MrRabbit said we add a domain option when  we find out that's a frequent issue. On domain change it's something that we fix quite quickly. Letting user change it by themselves createsd the fact that they won't report the issue and everyone would have to do it manually instead of getting a global fix. 

I vote to close this request
