### ISSUE TITLE
[UI Classic] Missing Tooltips for Header Navbar Icons

### ISSUE THREAD

**Issue by abhishek-exists** [manga-download/haruneko#729]
Hi Team,

I have noticed that the icons in the header navbar are not displaying tooltips correctly; they are misaligned and do not have any values. Instead, hovering over them shows `undefined`.

**Question**: Do we need to implement tooltips for these icons @Sheepux?

If so, we can add the following code to fix this issue, Please let me know if you would like me to raise a PR to implement this fix!

**Current behavior**:
<img width="189" alt="image" src="https://github.com/user-attachments/assets/e7edcb72-23f2-47ac-aee1-967bfdf2cfdc">
<img width="157" alt="image" src="https://github.com/user-attachments/assets/f371623c-14b3-4354-93ab-89f8f16351ee">
<img width="147" alt="image" src="https://github.com/user-attachments/assets/000973f7-e27c-4eaf-9e68-82df09c88839">

**Expected behavior**:
<img width="161" alt="image" src="https://github.com/user-attachments/assets/fad2cbdd-b6f5-4df4-9364-3ecbdf7a52af">
<img width="154" alt="image" src="https://github.com/user-attachments/assets/979f7ad0-73ef-4738-be8e-16341eb538c5">
<img width="136" alt="image" src="https://github.com/user-attachments/assets/cad03d02-d038-4336-b74c-242a86710aa2">

Lmk if you need a PR for this, Thanks

**Comment by Sheepux** [comment]
All the UI issues you're mentionning are due to the carbon framework upgrade. I've been on pause for a few months, I'll adress it but i was also hopping they'd release the new carbon v11 for svelte (still ongoing)
But perhaps the WIP could be good enougth (i need to check what kind of component i'm using) https://github.com/carbon-design-system/carbon-components-svelte/issues/1629
