### ISSUE TITLE
Generated Manga Folders Issue

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#888]
When downloading any manga, the folder created to contain the chapters has either issues:

1. The name of the folder is incomplete:

Manga Name: "The Reincarnated Assassin is a Genius Swordsman"
Folder Name: "The Reincarnated Assassin is a Genius Sw"
![image](https://github.com/user-attachments/assets/fa5aeae6-8854-4f88-9c34-41c2a671b433)

Maybe because of this limitation:
![image](https://github.com/user-attachments/assets/d903643e-016a-4896-8504-1191f884e703)

.

2. When I tried to move from Hakuneko to Haruneko, the created folders don't merge even though they have the same name without any difference.
![image](https://github.com/user-attachments/assets/4e2405c5-2341-4f38-8f59-5cbdcb2e6a18)

**Comment by MikeZeDev** [comment]
1) Website doesnt display the full name itself. Blame them.

![image](https://github.com/user-attachments/assets/c2166980-1f25-41f9-a5b7-c63b5c76168b)
![image](https://github.com/user-attachments/assets/d2832d4f-2d50-4e6e-9185-6e5bf2652c2d)

There is no ways to extract full name as its not on the page. Use another website is you want the full name as even if you use paste feature it will take the name from Manga list. 

2) I'd say perhaps its because of name characters cleaning. We improved that in Haruneko so your manga name look like be the same but it isnt. Its necessary to ensure folder and files names dont cause problems on different OS.

We are sorry for the inconvenient but you are on you own i guess. We are supporting bookmark migrations from Hakuneko to Haruneko but it doesnt cover downloaded content.

**Comment by Murshid7absi** [comment]
But if you go inside the manga page, you will find the full name, and maybe you can take that from there.
![image](https://github.com/user-attachments/assets/c51d6575-3adc-41ff-bd3a-7390c93f34d3)

it's better if you put it in the code for all the websites, you will avoid having complaints for every website naming(idk if i'm telling it right)

**Comment by Sheepux** [comment]
This is the first time someone complained about this and probably the only connector.
We cannot check each title when fetching the manga list (would generate too many requests). Manga name = manga name in the list and in your case it's truncated.
Cannot be fixed.

**Comment by MikeZeDev** [comment]
Like Sheep said, we already fetch each page of the manga list. If we had to fetch each page for each manga when fetching manga list not only 

* it would be making an exception for a website which is something to be avoided
* it would massively increase the time to get the list just for a couple of problematic mangas
* it would generate way to much requests for their servers and may force websites to use Cloudflare or other anti bots stuff and everyone will hate that.

If you really cant stand that bad title, manually empty manga list for asura and use clipboard method.
Press F12 > Application > IndexedDb > Hakuneko >MediasLists > find "AsuraScans" > delete the entry , restart haruneko

![image](https://github.com/user-attachments/assets/297a0b4b-9976-4629-8cef-d2b950d8901a)


Pasting feature will fetch manga page and provide real title.
