### ISSUE TITLE
Feature Request: Manga/Chapter Sorting

### ISSUE THREAD

**Issue by Murshid7absi** [manga-download/haruneko#889]
It would be efficient to add a sorting button/right-click option for the manga and the chapters like in HakuNeko:
![image](https://github.com/user-attachments/assets/64ac27e3-e5ef-45f9-8d8d-bf62d2d7ecd7)

Because some connectors manga are not organized (i.e. AsuraScans):
![image](https://github.com/user-attachments/assets/b96efb1d-4c63-482b-872d-bf4298c08d84)

**Comment by Sheepux** [comment]
I thought that I did an alpha sort on the names.
I'll do that this WE + sort option

**Comment by MikeZeDev** [comment]
We display chapters and manga as they are on the website now, that's all.  Ofc we are planning sorting options.

**Comment by Sheepux** [comment]
Alpha sorting at UI level for media names yes.
But for chapters it MUST be at the connector level (that's what was done in haku, some connectors had reverse sorting) as the UI cannot alpha sort as there are no correct rules for chapter sorting.

**Comment by MikeZeDev** [comment]
There are no problem to apply default sorting to manga chapters in plugin.
Does it means users wont be able to change chapters sorting at all ?

**Comment by Sheepux** [comment]
If we (human) find out when coding that it's reversed then add reverse in the code.
we did it in hakuneko for a good reason. Sometimes our code is fetching in reverse order for whatever reason. We need consistent behavior (user experience).

**Comment by Sheepux** [comment]
fixed by https://github.com/manga-download/haruneko/commit/2d60349d73c22d9d001a6438fa870c20fae37702 
item sort button is on bottom right

let me know if you encounter any issue

**Comment by MikeZeDev** [comment]
1) I am all for consistent user experience but if it turns out that we use a particular order by default (ie = in plugins) that is not website order we may encounter sorting issues and the user wont be pleased. Like you said , there is no magical formula.

I think keeping website order by default will achieve more consistency than any choice.

2) I am thinking in term of work and code changes. if we really have to apply "user sorting" at plugin level, we will have to revise a crap load of plugins, decorators and stuff. And i dont even see HOW we can achieve that for the moment.

I think there is no point in sorting chapters in plugins when imho its visual, therefore an UI/frontend thing. Ofc, it may seems i am pushing more work onto you but its what i think. Its not a fundamental thing like deduping which is rightfully backend work.

**Comment by Sheepux** [comment]
I don't get it: we already do reverse in some websites: 
https://github.com/manga-download/haruneko/blob/master/web/src/engine/websites/Kuaikanmanhua.ts#L21
why can't we do it on this one ?
