### ISSUE TITLE
Lack of ability to choose quality settings/force maximum quality for plugins/sites

### ISSUE THREAD

**Issue by minedo** [manga-download/haruneko#944]
In the original version of Hakuneko, the settings for certain connectors/plugins have an option to select the download quality for the scraped content. For example, BiliBili Manhua has "Quality Settings" ranging from "VeryPoor" to "VeryHigh", as well as the experimental option to "Force max quality".

Haruneko currently lacks this toggle/option, which causes scraped chapters to be downloaded in lower quality than what is actually possible. Scans for a certain series which the original Hakuneko would download at a resolution of 2000x3128 now download at a seemingly default resolution of 1600x2275.

I'm unsure if this should be cataloged as an "issue" or if it's a feature that's in the works, but it is a feature that is sorely missing for me right now and I'd greatly appreciate to know if it's going to be implemented in the near future.

**Comment by MikeZeDev** [comment]
Idk what you are talking about as we now force the use of the "very high " value .

https://github.com/manga-download/haruneko/blob/dd407f1f3486df88f10a6bfcc4ab2ffc94294333/web/src/engine/websites/BilibiliManhua.ts#L207

Since website is clearly making changes to fuck with us, i'd rather refrain to make this "force" setting available for now. Its already not easy to deal with this website dont wanna add an experimental thing.

**Comment by MikeZeDev** [comment]
More generally, we just download from the websites we cant chose quality most of the time.

When we can we always try to to fetch best quality for ANY website but you must understand that there is an unavoidable quality loss when a website scramble pictures, and that we have to ensure download went smoothly for everyone.

**Comment by ronny1982** [comment]
As of now, BiliBili is not (yet) part of of the product. You are free to discuss this topic in the pending PR #521
